[WIP] added backend directory and sql files
cs450-project/cs450-project pull request #3
Opened 2021-02-14 20:03 UTC by jrich8573

Added application backend directory and create table `sql` files. Continuing to work through the sql create table code.

2021-02-14 20:29 UTC, jrich8573 commented
TODO

- [ ] add last three sql files
- [ ] added `fk` and reference declarations within the `sql` code


Before merging the PR:
- [ ] test against dev env database
- [ ] push tables to production database

2021-02-15 01:28 UTC, jrich8573 commented
Added all create table `sql` files.

2021-02-15 13:30 UTC, lamalex commented on backend/sql/create_grants_entity.sql
> +           ,type char(8) check (type in ('external', 'internal'))
Inclined to say that strings like this should at least be ALL_CAPS like you have in UG/MS/PHP and ADMIN/FACULTY to differentiate them from arbitrary strings.

Even more inclined to make them integer values and then define an enum at the application level

2021-02-15 13:31 UTC, lamalex commented
How do you intend these to be run? Manually?

2021-02-15 13:43 UTC, jrich8573 commented on backend/sql/create_grants_entity.sql
> +           ,type char(8) check (type in ('external', 'internal'))
Internal/external should be all caps.

2021-02-15 13:45 UTC, jrich8573 commented on backend/sql/create_grants_entity.sql
> +           ,type char(8) check (type in ('external', 'internal'))
You can certainly enum them at the db level too. Either way works for me.

2021-02-15 15:12 UTC, jrich8573 commented on backend/sql/create_grants_entity.sql
> +           ,type char(8) check (type in ('external', 'internal'))
@lamalex locally I will create them manually, however, I think we need to have a more in-depth architecture conversation around the database. I am not opposed to scripting (which I am doing locally within my db container) the production creation. 

I am a little confused to your follow up questions. I would assume we will use GH for change management. I will add the drop table functional to the scripts later today, which to allow up to check for the existence of a not null table and, and if not null, we can drop and re create. 

One note, the create table code should only run on demand, not as a stage (or step) of the CI/CD pipeline.

2021-02-17 23:56 UTC, lamalex commented on backend/scripts/sql_run.sh
> +		exit
I think we should set a non-zero exit code here. Server being down seem like a condition we’d want to consider a failure case.

2021-02-17 23:56 UTC, lamalex commented on backend/scripts/sql_run.sh
> +		   @$file;
You’re running these interactively in the mysql repl right? Is there a reason you’re not using stdin? 
`mysql -s ${user}/${password}@${host}/${service} < <filename.sql>`

2021-02-17 23:56 UTC, lamalex commented on backend/sql/create_grants.sql
> +create table tbl_fact_grants(
I think in my PR #2 you asked about checking if the tables exist. You can do `CREATE IF NOT EXISTS` which will only execute your `create` statement if the tables haven’t been created.

2021-02-18 00:02 UTC, jrich8573 commented on backend/scripts/sql_run.sh
> +		   @$file;
@lamalex I really just want a way to auto the table build (and any other sql related data structure). We could run these at the shell, but I would prefer auto builds as we promote into prod.

2021-02-18 00:03 UTC, jrich8573 commented on backend/scripts/sql_run.sh
> +		exit
@lamalex yup. This is untested at this point. Just putting thoughts down first, and I will refine within my env before merging into master

2021-02-18 00:04 UTC, jrich8573 commented on backend/sql/create_grants.sql
> +create table tbl_fact_grants(
@lamalex that kind of what I thought too, just making sure we are on the same page.

2021-02-18 00:11 UTC, lamalex commented
Yeah we can totally do that. I have duty tonight but I can pair on it tomorrow with you if you want

— Alex Launi

> On Feb 17, 2021, at 19:06, Jason Rich <notifications@github.com> wrote:
> 
> ﻿
> @jrich8573 commented on this pull request.
> 
> In backend/scripts/sql_run.sh:
> 
> > +		echo "`date` :Exiting bash script..."
> +		exit
> +	fi
> +	echo "`date` :DB status check completed"
> +	echo "`date` :Connecting To ${user}/******@${service}";
> +	if [[ $DB_STATUS == "UP" ]]
> +	then
> +		for file in `dir -d $master`;
> +		do
> +		#for file in `cat extrasqlslist.txt` ;do
> +		   echo "`date`:Executing file $file...";
> +		   echo "`date`:__________________________________________";
> +		   echo "`date`:SQL OUTPUT:";
> +		   echo "`date`:__________________________________________";
> +		   mysql -s ${user}/${password}@${host}/${service}<<-EOF
> +		   @$file;
> @lamalex I really just want a way to auto the table build (and any other sql related data structure). We could run these at the shell, but I would prefer auto builds as we promote into prod.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2021-02-18 00:37 UTC, jrich8573 commented
@lamalex no worries. Tomorrow evening works for me. Be safe.

2021-02-22 03:41 UTC, jrich8573 commented
Removed all `FK` references, will need to run the following after migration:

```sql
ALTER TABLE <<table_name>> ADD FOREIGN KEY <<key>> REFERENCES <<table(key)>>;
```

Tested against `mysql` latest container, by creating all tables manually. Did not test using the `sql_run.sh` script.

2021-02-22 14:51 UTC, lamalex requested changes

2021-02-22 14:51 UTC, lamalex commented on db/sql/006_create_purchases.sql
> +       ,cancel_date datetime
Same as above, recommend TimeStamp

2021-02-22 14:51 UTC, lamalex commented on db/sql/008_create_grants.sql
> +       ,active varchar(7) check (active in ('PENDING','APPROVED', 'DENIED'))
ENUM is a safer and less verbose DT for list of string values

2021-02-22 15:09 UTC, lamalex requested changes
There are no foreign keys declared. Was the intentional?
Additionally I'm hesitant to add a bunch of tables before we need them. I'd rather add them as we build, but I'm not married to either way

2021-02-22 15:09 UTC, lamalex commented on db/sql/003_create_users.sql
> +       department int UNSIGNED NOT NULL,
shouldn't this be a foreign key?

2021-02-22 15:09 UTC, lamalex commented on db/sql/004_create_students.sql
> +        department smallint UNSIGNED,
same as above, foreign key?

2021-03-21 19:58 UTC, jrich8573 commented
- [ ] need to edit grants table make grant_number an unsigned int 
- [ ] need to add  FK references

2021-04-04 14:00 UTC, lamalex commented
Closing due to merging #12 which superceded this one

2021-04-04 14:00 UTC, closed without merging